"""Semantic repairs applied during consolidation.

Each function here fixes a defect found by the 2026-07-14 audit
(docs/kg_audit_2026-07-14.md). They run inside `consolidate()`; every one
writes a traceability artefact next to the KG so the rewrite can be inspected.
"""
from __future__ import annotations

import json
import logging
from pathlib import Path

import polars as pl
from rdkit import Chem, RDLogger

RDLogger.DisableLog("rdApp.*")

from vsleakkg.kg.schema import EdgeType, NodeType

log = logging.getLogger(__name__)

# Decoy-protocol classes. The old graph had one DecoyProtocol node per corpus,
# which made the axis a relabelling of the source axis: every protocol sat
# inside exactly one corpus, so it contributed no path the source axis did not
# already give. These classes describe HOW the inactive label was produced, so
# they span corpora and carry real leakage paths. Only inactives are linked —
# an active compound is not a product of a decoy-generation protocol.
# ONLY artificial protocols belong here. Proposal Table 2 defines this axis as
# "Same artificial decoy protocol -> prevent benchmark-source shortcuts": it
# exists to catch shortcuts that a decoy-GENERATION procedure bakes in.
#
# LIT-PCBA and BigBind inactives are *experimentally measured* — real assay
# readouts, not artefacts. Linking their 2.74 M examples through a shared
# "experimental_inactive" node would fabricate a leakage path that does not
# exist, and hand it weight 0.50. They deliberately get no protocol edge.
DECOY_PROTOCOL: dict[str, tuple[str, str]] = {
    # corpus -> (its own protocol node, the method class that protocol implements)
    "DUD-E":     ("property_matched", "Property-matched, topologically dissimilar decoys"),
    "DEKOIS":    ("property_matched", "Property-matched, topologically dissimilar decoys"),
    "BayesBind": ("random_library", "Random library sample as putative inactive"),
    # LIT-PCBA and BigBind inactives are experimentally MEASURED, not generated by a
    # protocol. They deliberately get no protocol edge: linking them would fabricate
    # a leakage path where none exists.
}


def _flatten_smiles(smi: str) -> str:
    """Canonical SMILES with stereochemistry removed.

    The first cut of this merge simply deleted `/`, `\\` and `@` from the SMILES
    string. That under-merges: two molecules with the same flat framework can have
    stereo-bearing canonical SMILES whose atom ORDER differs, so the stripped
    strings differ too and the nodes never meet. Measured miss rate ~0.16 %
    (~915 Scaffold nodes). Re-canonicalising with RDKit keys the node on the
    chemistry rather than on the spelling.

    Unparseable SMILES (a handful of RDKit Murcko artefacts, present in the
    inherited KG as well) fall back to the string-stripped form so the node
    survives rather than silently collapsing into a null group.
    """
    m = Chem.MolFromSmiles(smi)
    if m is None:
        return smi.replace("/", "").replace("\\", "").replace("@", "")
    Chem.RemoveStereochemistry(m)
    return Chem.MolToSmiles(m)


def stable_unique(df: pl.DataFrame, subset: list[str]) -> pl.DataFrame:
    """Deterministic replacement for `unique(subset=..., keep="first")`.

    `keep="first"` is NOT deterministic. polars is multithreaded, so which of two
    duplicate rows arrives "first" varies between runs — and with it the `label` and
    `props` that survive. Two consecutive builds of identical code over identical
    input produced graphs with the same node and edge SETS but different labels,
    which means a rebuild can never be verified against the shipped KG. Sorting on
    every column first makes the choice total.
    """
    return df.sort(df.columns).unique(subset=subset, keep="first")


def _rewrite(edges: pl.DataFrame, mapping: pl.DataFrame) -> pl.DataFrame:
    """Apply an old_id -> new_id mapping to both edge endpoints."""
    out = edges
    for side in ("src", "dst"):
        out = (out.join(mapping, left_on=side, right_on="old_id", how="left")
                  .with_columns(pl.coalesce([pl.col("new_id"), pl.col(side)]).alias(side))
                  .drop("new_id"))
    return out


def apply_protein_id_map(
    nodes: pl.DataFrame, edges: pl.DataFrame, processed: Path
) -> tuple[pl.DataFrame, pl.DataFrame, int]:
    """Defect 1 — the protein axis was blind to 81.7 % of Examples.

    DUD-E / DEKOIS / LIT-PCBA name their targets by gene symbol, so their loaders
    emit `tgt:<Corpus>:<gene>` Protein nodes. MMseqs2 only clusters
    UniProt-anchored `protein:<accession>` nodes, so the primary target of nearly
    every benchmark example sat outside the clustering entirely.

    `tools/resolve_targets.py` resolves each target to a UniProt accession from
    two independent routes; this applies that map. Collapsing the ids also makes
    cross-corpus protein leakage visible for the first time — DUD-E `hs90a` and
    DEKOIS `hsp90` become the same node.
    """
    f = processed / "protein_id_map.parquet"
    if not f.exists():
        log.warning("protein_id_map.parquet missing — protein axis stays blind")
        return nodes, edges, 0
    mapping = pl.read_parquet(f).select("old_id", "new_id").pipe(stable_unique, ["old_id"])
    if not mapping.height:
        return nodes, edges, 0
    # NB: no filter on "ids present in nodes" — this function is called a second
    # time AFTER _wire_reference_provenance, which re-emits example_has_protein
    # edges straight from the raw BindingDB frame and therefore reintroduces the
    # malformed ids (`protein:<acc1> <acc2>`) that the first pass had removed.

    nodes_out = (
        nodes.join(mapping, left_on="node_id", right_on="old_id", how="left")
             .with_columns(
                 pl.coalesce([pl.col("new_id"), pl.col("node_id")]).alias("node_id"),
                 pl.when(pl.col("new_id").is_not_null())
                   .then(pl.lit(NodeType.PROTEIN.value))
                   .otherwise(pl.col("node_type")).alias("node_type"))
             .drop("new_id")
             .pipe(stable_unique, ["node_id"])
    )
    edges_out = _rewrite(edges, mapping)
    return nodes_out, edges_out, mapping.height


def merge_stereo_scaffolds(
    nodes: pl.DataFrame, edges: pl.DataFrame, out_dir: Path
) -> tuple[pl.DataFrame, pl.DataFrame, int]:
    """Defect 3 — 10.4 % of Scaffold nodes were stereochemical duplicates.

    A Bemis-Murcko scaffold is a topological object: two stereoisomers share it.
    The loaders keyed Scaffold nodes on the stereo-bearing SMILES, so the same
    framework became several nodes and a scaffold-clean split leaked — two
    examples on one scaffold landed on opposite sides because the graph thought
    their scaffolds differed.

    The ligand axis is already protected against exactly this by the
    `ligand_exact` / `ligand_fingerprint_exact` bridges; the scaffold axis had no
    equivalent. Here we key the node on the stereo-free SMILES instead, keeping
    the lexicographically smallest node_id of each group as canonical.
    """
    sc = nodes.filter(pl.col("node_type") == NodeType.SCAFFOLD.value)
    if not sc.height:
        return nodes, edges, 0
    flat = sc.with_columns(
        pl.col("label").map_elements(_flatten_smiles, return_dtype=pl.Utf8).alias("_flat"))
    canon = (flat.group_by("_flat")
                 .agg(pl.col("node_id").min().alias("new_id"),
                      pl.len().alias("k")))
    mapping = (flat.join(canon, on="_flat")
                   .filter(pl.col("node_id") != pl.col("new_id"))
                   .select(pl.col("node_id").alias("old_id"), "new_id"))
    if not mapping.height:
        return nodes, edges, 0

    out_dir.mkdir(parents=True, exist_ok=True)
    mapping.write_parquet(out_dir / "scaffold_stereo_merge_map.parquet")

    merged = set(mapping["old_id"].to_list())
    nodes_out = nodes.filter(~pl.col("node_id").is_in(list(merged)))
    # The surviving node now denotes the *flat* framework, so its label must be
    # the stereo-free SMILES. Leaving one arbitrary stereoisomer's SMILES there
    # would make the label disagree with the identity the node actually carries.
    relabel = (canon.select(pl.col("new_id").alias("node_id"),
                            pl.col("_flat").alias("_lbl"),
                            pl.col("k").alias("_k")))
    nodes_out = (nodes_out.join(relabel, on="node_id", how="left")
                 .with_columns(
                     pl.coalesce([pl.col("_lbl"), pl.col("label")]).alias("label"),
                     pl.when(pl.col("_k") > 1)
                       .then(pl.lit('{"stereo_merged":true}'))
                       .otherwise(pl.col("props")).alias("props"))
                 .drop("_lbl", "_k"))
    edges_out = _rewrite(edges, mapping)
    # the rewrite can now point several ligand_scaffold edges at one scaffold
    edges_out = edges_out.pipe(stable_unique, ["src", "dst", "edge_type"])
    return nodes_out, edges_out, mapping.height


def one_scaffold_per_ligand(edges: pl.DataFrame) -> tuple[pl.DataFrame, int]:
    """Residual of defect 3 — 18 Ligands still carried two scaffolds.

    These are not stereo variants but protonation variants of one framework
    (`[NH2+]=C1...` vs `[N+]=C1...`), produced when different loaders sanitised
    the same N-oxide differently. A Bemis-Murcko scaffold is one per molecule by
    definition, so keep the lexicographically smallest and drop the rest; the
    orphaned scaffold node is removed by the orphan pass.
    """
    m = pl.col("edge_type") == EdgeType.LIGAND_SCAFFOLD.value
    sc = edges.filter(m)
    keep = sc.group_by("src").agg(pl.col("dst").min().alias("dst"))
    dropped = sc.height - keep.height
    if not dropped:
        return edges, 0
    rebuilt = keep.select(
        "src", "dst",
        pl.lit(EdgeType.LIGAND_SCAFFOLD.value).alias("edge_type"),
        pl.lit("{}").alias("props"))
    return pl.concat([edges.filter(~m), rebuilt], how="vertical_relaxed"), dropped


FINGERPRINT_EXACT_T = 0.9995


def relabel_identical_similars(edges: pl.DataFrame) -> tuple[pl.DataFrame, int]:
    """`ligand_similar` edges at Tanimoto >= 0.9995 are not "similar" — they are the
    same molecule as far as ECFP4 can tell (stereo / tautomer the fingerprint does
    not encode). The v3 build relabelled 314,683 such edges to
    `ligand_fingerprint_exact` (weight 0.95); 123 were missed and still sit in
    `ligand_similar` at weight 0.65, which UNDERSTATES the leak they represent.
    """
    m = pl.col("edge_type") == EdgeType.LIGAND_SIMILAR.value
    t = pl.col("props").str.json_path_match("$.tanimoto").cast(pl.Float64, strict=False)
    hit = m & (t >= FINGERPRINT_EXACT_T)
    n = edges.filter(hit).height
    if not n:
        return edges, 0
    out = edges.with_columns(
        pl.when(hit)
          .then(pl.lit(EdgeType.LIGAND_FINGERPRINT_EXACT.value))
          .otherwise(pl.col("edge_type"))
          .alias("edge_type"))
    return out.pipe(stable_unique, ["src", "dst", "edge_type"]), n


def sort_ligand_pairs(edges: pl.DataFrame) -> tuple[pl.DataFrame, int]:
    """Defect 5 — `ligand_exact` / `ligand_parent_exact` were not sorted pairs.

    3,477 of 6,939 edges in each type had `src > dst`. Nothing was double-counted,
    but the order was arbitrary while the sibling types (`ligand_fingerprint_exact`,
    `ligand_similar`) do use the sorted convention — and kg_build_history.md
    wrongly asserted these two did as well. Any downstream lookup keyed on a
    sorted pair silently missed half the exact-ligand bridges.
    """
    # All four ligand-ligand pair types, not just the two that were broken: the
    # relabel step above moves edges between them, so sorting a subset means the
    # invariant depends on which order the fixes happen to run in.
    types = [EdgeType.LIGAND_EXACT.value,
             EdgeType.LIGAND_PARENT_EXACT.value,
             EdgeType.LIGAND_FINGERPRINT_EXACT.value,
             EdgeType.LIGAND_SIMILAR.value]
    m = pl.col("edge_type").is_in(types) & (pl.col("src") > pl.col("dst"))
    n = edges.filter(m).height
    if not n:
        return edges, 0
    out = edges.with_columns(
        pl.when(m).then(pl.col("dst")).otherwise(pl.col("src")).alias("_s"),
        pl.when(m).then(pl.col("src")).otherwise(pl.col("dst")).alias("_d"),
    ).with_columns(pl.col("_s").alias("src"), pl.col("_d").alias("dst")).drop("_s", "_d")
    out = out.pipe(stable_unique, ["src", "dst", "edge_type"])
    return out, n


def drop_ligandless_examples(
    nodes: pl.DataFrame, edges: pl.DataFrame
) -> tuple[pl.DataFrame, pl.DataFrame, int]:
    """Defect 6 — 4 DUD-E Examples had no Ligand (unparseable SMILES).

    They can never be scored on the ligand or scaffold axis, so they are dropped
    rather than left as silent holes.
    """
    ex = nodes.filter(pl.col("node_type") == NodeType.EXAMPLE.value).select("node_id")
    has_lig = (edges.filter(pl.col("edge_type") == EdgeType.EXAMPLE_HAS_LIGAND.value)
                    .select(pl.col("src").alias("node_id")).unique())
    bad = ex.join(has_lig, on="node_id", how="anti")
    if not bad.height:
        return nodes, edges, 0
    dead = bad["node_id"].to_list()
    nodes_out = nodes.filter(~pl.col("node_id").is_in(dead))
    edges_out = edges.filter(~(pl.col("src").is_in(dead) | pl.col("dst").is_in(dead)))
    return nodes_out, edges_out, len(dead)


def rebuild_decoy_protocol(
    nodes: pl.DataFrame, edges: pl.DataFrame
) -> tuple[pl.DataFrame, pl.DataFrame, dict[str, int]]:
    """Two-tier decoy provenance, and only for inactives.

    The inherited graph had one DecoyProtocol node per corpus joined to EVERY example
    of that corpus, actives included — although an active compound is not a product of
    a decoy-generation procedure. And because each protocol sat inside exactly one
    corpus, the partition it induced was identical to the source partition, while
    carrying a higher weight (0.50 vs 0.35): the axis added nothing.

    Two tiers, because these are two different facts:

        Example(inactive) --source_decoy_protocol--> proto:DUD-E
        proto:DUD-E       --decoy_protocol_in_class--> protoclass:property_matched
        proto:DEKOIS      --decoy_protocol_in_class--> protoclass:property_matched

    "DUD-E used a property-matched decoy procedure" is a fact the benchmark states.
    "DUD-E's and DEKOIS's procedures are the same kind of thing" is an inference. Both
    are recorded, separately, and the downstream step chooses whether to traverse the
    class tier (i.e. whether a DUD-E decoy and a DEKOIS decoy share a leakage path).
    """
    edges = edges.filter(~pl.col("edge_type").is_in(
        [EdgeType.SOURCE_DECOY_PROTOCOL.value, EdgeType.DECOY_PROTOCOL_IN_CLASS.value]))
    nodes = nodes.filter(~pl.col("node_type").is_in(
        [NodeType.DECOY_PROTOCOL.value, NodeType.DECOY_PROTOCOL_CLASS.value]))

    src_of = (edges.filter(pl.col("edge_type") == EdgeType.EXAMPLE_FROM_SOURCE.value)
                   .select(pl.col("src").alias("ex"),
                           pl.col("dst").str.replace("^src:", "").alias("corpus")))
    labels = (nodes.filter(pl.col("node_type") == NodeType.EXAMPLE.value)
                   .select(pl.col("node_id").alias("ex"),
                           pl.col("props").str.json_path_match("$.label").alias("label")))
    inactive = src_of.join(labels, on="ex").filter(pl.col("label") == "0")

    spec = pl.DataFrame([{"corpus": c, "method": m, "desc": d}
                         for c, (m, d) in DECOY_PROTOCOL.items()])
    linked = inactive.join(spec, on="corpus")
    if not linked.height:
        return nodes, edges, {}

    used = linked.select("corpus", "method", "desc").unique().sort("corpus")

    proto_nodes = pl.DataFrame({
        "node_id":   [f"proto:{c}" for c in used["corpus"]],
        "node_type": [NodeType.DECOY_PROTOCOL.value] * used.height,
        "label":     used["desc"].to_list(),
        "props":     [json.dumps({"corpus": c, "method": m}, sort_keys=True)
                      for c, m in zip(used["corpus"], used["method"])],
    })
    cls = sorted(set(used["method"].to_list()))
    class_nodes = pl.DataFrame({
        "node_id":   [f"protoclass:{m}" for m in cls],
        "node_type": [NodeType.DECOY_PROTOCOL_CLASS.value] * len(cls),
        "label":     cls,
        "props":     [json.dumps({"kind": "decoy_generation_method"})] * len(cls),
    })

    ex_edges = linked.select(
        pl.col("ex").alias("src"),
        (pl.lit("proto:") + pl.col("corpus")).alias("dst"),
        pl.lit(EdgeType.SOURCE_DECOY_PROTOCOL.value).alias("edge_type"),
        pl.lit("{}").alias("props"),
    ).pipe(stable_unique, ["src", "dst"])

    cls_edges = used.select(
        (pl.lit("proto:") + pl.col("corpus")).alias("src"),
        (pl.lit("protoclass:") + pl.col("method")).alias("dst"),
        pl.lit(EdgeType.DECOY_PROTOCOL_IN_CLASS.value).alias("edge_type"),
        pl.lit("{}").alias("props"),
    ).pipe(stable_unique, ["src", "dst"])

    nodes = pl.concat([nodes, proto_nodes, class_nodes], how="vertical_relaxed")
    edges = pl.concat([edges, ex_edges, cls_edges], how="vertical_relaxed")
    counts = dict(linked.group_by("corpus").agg(pl.len().alias("n")).iter_rows())
    counts["_classes"] = len(cls)
    return nodes, edges, counts



def drop_placeholder_publications(
    nodes: pl.DataFrame, edges: pl.DataFrame, chembl_db: Path
) -> tuple[pl.DataFrame, int]:
    """ChEMBL `doc_type = 'DATASET'` rows are not publications.

    `CHEMBL1201862` ("PubChem BioAssay data set") alone linked 1,730,288 examples —
    34 % of the graph — through a single Publication node. Two examples that both
    came out of a PubChem dump do not share a paper; they share nothing. 279 such
    placeholder docs carried 1,996,399 of the publication edges and collapsed the
    publication axis into one group covering 95 % of examples.

    Real PUBLICATION (64,757 docs, ~40 examples each), PATENT and BOOK rows are
    kept — a shared patent IS shared provenance.
    """
    import sqlite3
    if not Path(chembl_db).exists():
        log.warning("ChEMBL db missing — cannot filter placeholder publications")
        return edges, 0
    con = sqlite3.connect(str(chembl_db))
    bad = {f"chembl_doc:{r[0]}" for r in
           con.execute("select chembl_id from docs where doc_type = 'DATASET'")}
    con.close()
    if not bad:
        return edges, 0
    m = ((pl.col("edge_type") == EdgeType.EXAMPLE_FROM_PUBLICATION.value)
         & pl.col("dst").is_in(list(bad)))
    n = edges.filter(m).height
    return edges.filter(~m), n

def split_example_protein_relation(
    nodes: pl.DataFrame, edges: pl.DataFrame, processed: Path
) -> tuple[pl.DataFrame, int, int]:
    """`example_has_protein` was carrying two different relations at once.

    5,025,493 edges said "this example's TARGET is P" (one per example, from the
    corpus loader). 2,890,812 more said "this example's LIGAND was once measured
    against P" (from the BindingDB wire). Those are not the same claim, and merging
    them is not a rounding error: 550,031 examples ended up with several proteins,
    each acting as a bridge, and the protein axis collapsed into ONE leakage group
    covering 100 % of examples — a protein-clean split was impossible.

    With only the target edges the axis behaves: 1,135 groups at 90 % identity,
    largest 7.2 %.

    The BindingDB relation is not discarded — it is retyped Ligand -> Protein as
    `ligand_measured_protein`, outside every leakage axis. It is real evidence of
    *pretraining* contamination, which is a different question from benchmark-split
    leakage.
    """
    f = processed / "protein_id_map.parquet"
    if not f.exists():
        return edges, 0, 0
    im = pl.read_parquet(f).select(pl.col("old_id").alias("tgt_id"),
                                   pl.col("new_id").alias("true_prot"))

    ehp = edges.filter(pl.col("edge_type") == EdgeType.EXAMPLE_HAS_PROTEIN.value)
    rest = edges.filter(pl.col("edge_type") != EdgeType.EXAMPLE_HAS_PROTEIN.value)

    tagged = (ehp.with_columns(
                  (pl.lit("tgt:") + pl.col("src").str.split(":").list.get(1)
                   + pl.lit(":") + pl.col("src").str.split(":").list.get(2)).alias("tgt_id"))
                 .join(im, on="tgt_id", how="left"))
    keep = tagged.filter(pl.col("dst") == pl.col("true_prot")).select(
        "src", "dst", "edge_type", "props")
    other = tagged.filter((pl.col("true_prot").is_null())
                          | (pl.col("dst") != pl.col("true_prot")))

    ex2lig = (edges.filter(pl.col("edge_type") == EdgeType.EXAMPLE_HAS_LIGAND.value)
                   .select(pl.col("src").alias("ex"), pl.col("dst").alias("lig")))
    measured = (other.select(pl.col("src").alias("ex"), "dst")
                     .join(ex2lig, on="ex")
                     .select(pl.col("lig").alias("src"), "dst",
                             pl.lit(EdgeType.LIGAND_MEASURED_PROTEIN.value).alias("edge_type"),
                             pl.lit("{}").alias("props"))
                     .pipe(stable_unique, ["src", "dst"]))

    out = pl.concat([rest, keep, measured], how="vertical_relaxed")
    return out, other.height, measured.height


def validate_canonical(nodes: pl.DataFrame, edges: pl.DataFrame) -> None:
    """Refuse to write a corrupt KG. Runs immediately before the parquet write.

    polars on this box intermittently corrupts string columns when the machine is
    heavily loaded — the same null-byte class of bug that the v3 build history
    records against `task_build_kg`. It is NOT deterministic: two consecutive runs of
    identical code over identical input produced 38,549,309 edges (with `edge_type`
    values like `'\x00\x00\x00mple_has_ligand'`) and 38,547,837 edges (clean).

    `task_build_kg` grew write-time invariants after that incident. `consolidate`
    never did, so a corrupt canonical KG could be written and audited later — or
    worse, not audited at all. A bad run now dies instead of shipping a graph whose
    leakage numbers would be quietly wrong.
    """
    problems: list[str] = []
    node_types = {t.value for t in NodeType}
    edge_types = {t.value for t in EdgeType}

    for frame, cols, name in ((nodes, ["node_id", "node_type"], "nodes"),
                              (edges, ["src", "dst", "edge_type"], "edges")):
        for c in cols:
            bad = frame.filter(pl.col(c).str.contains("\x00")).height
            if bad:
                sample = frame.filter(pl.col(c).str.contains("\x00"))[c].head(3).to_list()
                problems.append(f"{name}.{c}: {bad:,} value(s) contain NUL bytes, e.g. {sample!r}")

    unknown_n = set(nodes["node_type"].unique().to_list()) - node_types
    if unknown_n:
        problems.append(f"nodes.node_type not in schema: {sorted(unknown_n)!r}")
    unknown_e = set(edges["edge_type"].unique().to_list()) - edge_types
    if unknown_e:
        problems.append(f"edges.edge_type not in schema: {sorted(unknown_e)!r}")

    dup = nodes.group_by("node_id").len().filter(pl.col("len") > 1).height
    if dup:
        problems.append(f"{dup:,} duplicate node_id")

    ids = nodes.select("node_id")
    for side in ("src", "dst"):
        d = edges.join(ids, left_on=side, right_on="node_id", how="anti").height
        if d:
            problems.append(f"{d:,} dangling edges on {side}")

    if problems:
        raise RuntimeError(
            "canonical KG failed write-time validation — REFUSING to write.\n  "
            + "\n  ".join(problems)
            + "\n\nIf the failures are NUL bytes this is the intermittent polars "
              "string-corruption bug: the run is bad, not the code. Re-run consolidate."
        )
